import puppeteer from "puppeteer";
const browser = await puppeteer.launch({ headless: true, args: ["--enable-unsafe-swiftshader","--no-sandbox","--mute-audio"] });
const page = await browser.newPage();
await page.setViewport({ width: 1280, height: 720 });
const fails = [];
page.on("requestfailed", (r) => fails.push(r.url().slice(0, 100)));
page.on("response", (r) => { if (r.status() >= 400) fails.push(`${r.status()} ${r.url().slice(0, 100)}`); });
page.on("pageerror", (e) => console.log("[pageerror]", e.message));
await page.goto("https://taehyeung123.github.io/DEEPRED-HOME/", { waitUntil: "networkidle2", timeout: 90000 });
await page.waitForFunction(() => document.querySelector(".preloader")?.classList.contains("done"), { timeout: 40000 });
await new Promise((r) => setTimeout(r, 6000));
await page.screenshot({ path: "shots-m/live-hero.png" });
const scrollEnd = await page.evaluate(() => window.innerHeight * 14);
await page.evaluate((y) => window.scrollTo(0, y), Math.round(scrollEnd * 0.31));
await new Promise((r) => setTimeout(r, 2800));
await page.screenshot({ path: "shots-m/live-panel.png" });
console.log("failed requests:", fails.length ? fails.slice(0, 8) : "none");
await browser.close();
console.log("live check done");
